// Curated overrides for the marketable core.
//
// Why this exists: both raw publisher signals are corrupt. `gcd_series.
// publisher_gcd_id` is scrambled (the US Marvel ThunderCats links to a Spanish
// publisher), and `cv_publisher` was mass-stamped by the cover ingest's
// title-only ComicVine match (every "Thundercats" series got "Marvel",
// including the 2024 Dynamite run and foreign reprints). So for the series
// collectors actually search, we pin verified values here instead of trusting
// the firehose.
//
// Keyed by gcd_id. Applied in scripts/refreshSeriesSearchCache.js, overriding
// the computed resolved_publisher_cached / year span before they're written to
// the series cache.
//
// Suppression mechanism: setting `publisher` to a non-US house (e.g.
// "Marvel UK") naturally drops the row from US search via the existing
// US_PUBLISHER_ALLOWLIST filter — correct attribution doubles as suppression,
// no separate flag needed. For a US row you want hidden anyway, use
// `hide: true`.
//
// `// VERIFY` marks a best-guess to confirm.
export const SERIES_OVERRIDES = {
  // ── ThunderCats (proof case) ───────────────────────────────────────────
  3055:   { publisher: "Marvel Comics" },          // 1985–1988 Star/Marvel — the canonical US run
  208797: { publisher: "Dynamite Entertainment" }, // 2024 Dynamite relaunch (was mislabeled Marvel)
  61431:  { publisher: "Marvel UK" },              // 1987–1990 UK weekly — non-US → drops from US search
  10331:  { publisher: "WildStorm" },              // 2002 WildStorm relaunch  // VERIFY
  23875:  { publisher: "WildStorm" },              // 2003–2005 WildStorm       // VERIFY

  // ── Topps Comics (1992–1998) ───────────────────────────────────────────
  // Topps Comics was a real US publisher (Bram Stoker's Dracula, X-Files,
  // Mars Attacks, Jurassic Park, Zorro, Mary Shelley's Frankenstein, etc.).
  // Almost their entire catalog landed in `series` with resolved_publisher
  // = "Unknown Publisher" because gcd_series.publisher_gcd_id is scrambled
  // (doesn't match the actual Topps rows in gcd_publishers: 188/197/198/
  // 2811/9910) and cv_publisher is null for most of these. Without these
  // overrides every Topps book is filtered out of US search.
  //
  // Cohort generated by cross-referencing the ComicVine Topps publisher
  // catalog against our `series` table, filtered to:
  //   - year_start in 1992–1998 (Topps' actual operating years)
  //   - resolved_publisher_cached = "Unknown Publisher" (clearly broken)
  //   - English title (excludes foreign reprints)
  //   - not Star Wars: Tales of the Jedi (Dark Horse, except the Topps Ashcan)
  4620: { publisher: "Topps Comics" }, // 1992 Bram Stoker's Dracula (Coppola film adaptation, 4-issue mini)
  4898: { publisher: "Topps Comics" }, // 1993 Zorro
  49990: { publisher: "Topps Comics" }, // 1994 Jurassic Park Adventures
  5170: { publisher: "Topps Comics" }, // 1994 Cadillacs and Dinosaurs
  16477: { publisher: "Topps Comics" }, // 1995 Return to Jurassic Park
  15331: { publisher: "Topps Comics" }, // 1994 Duckman
  5430: { publisher: "Topps Comics" }, // 1995 Lady Rawhide
  4932: { publisher: "Topps Comics" }, // 1993 Ray Bradbury Comics
  5660: { publisher: "Topps Comics" }, // 1996 Lady Rawhide
  5658: { publisher: "Topps Comics" }, // 1996 Hercules: The Legendary Journeys
  37998: { publisher: "Topps Comics" }, // 1995 The X-Files Special Edition
  4893: { publisher: "Topps Comics" }, // 1993 Jack Kirby's Secret City Saga
  4895: { publisher: "Topps Comics" }, // 1993 Jurassic Park
  36626: { publisher: "Topps Comics" }, // 1997 The Lost World: Jurassic Park
  15153: { publisher: "Topps Comics" }, // 1994 Mary Shelley's Frankenstein
  16214: { publisher: "Topps Comics" }, // 1997 The X-Files: Ground Zero
  20546: { publisher: "Topps Comics" }, // 1993 Jurassic Park
  4894: { publisher: "Topps Comics" }, // 1993 Jack Kirby's TeenAgents
  4897: { publisher: "Topps Comics" }, // 1993 Satan's Six
  49839: { publisher: "Topps Comics" }, // 1994 Jurassic Park: Raptors Attack
  49991: { publisher: "Topps Comics" }, // 1994 Jurassic Park: Raptors Hijack
  5171: { publisher: "Topps Comics" }, // 1994 The Lone Ranger and Tonto
  20816: { publisher: "Topps Comics" }, // 1996 Mars Attacks The Savage Dragon
  5903: { publisher: "Topps Comics" }, // 1997 Xena: Warrior Princess / Joxer: Warrior Prince
  4892: { publisher: "Topps Comics" }, // 1993 Dracula: Vlad the Impaler
  15580: { publisher: "Topps Comics" }, // 1997 Jackie Chan's Spartan X: The Armour of Heaven
  15332: { publisher: "Topps Comics" }, // 1994 Duckman: The Mob Frog Saga
  6093: { publisher: "Topps Comics" }, // 1998 Xena: Warrior Princess vs Callisto
  6091: { publisher: "Topps Comics" }, // 1998 Xena: Warrior Princess: The Orpheus Trilogy
  14460: { publisher: "Topps Comics" }, // 1995 Jason vs. Leatherface
  15155: { publisher: "Topps Comics" }, // 1996 Space: Above and Beyond
  5904: { publisher: "Topps Comics" }, // 1997 Xena: Warrior Princess / The Dragon's Teeth
  6089: { publisher: "Topps Comics" }, // 1998 Xena: Warrior Princess: And the Original Olympics
  10566: { publisher: "Topps Comics" }, // 1995 The X-Files Comics Digest
  14431: { publisher: "Topps Comics" }, // 1994 Satan's Six: Hellspawn
  14459: { publisher: "Topps Comics" }, // 1993 Jason Goes to Hell The Final Friday
  50739: { publisher: "Topps Comics" }, // 1995 The X-Files Collection
  144395: { publisher: "Topps Comics" }, // 1996 The X-Files Magazine
  6092: { publisher: "Topps Comics" }, // 1998 Xena: Warrior Princess: The Wrath of Hera
  12889: { publisher: "Topps Comics" }, // 1996 Space: Above And Beyond -- The Gauntlet
  5431: { publisher: "Topps Comics" }, // 1995 The X-Files Annual
  4891: { publisher: "Topps Comics" }, // 1993 Dracula Versus Zorro
  6090: { publisher: "Topps Comics" }, // 1998 Xena: Warrior Princess: Bloodlines
  21645: { publisher: "Topps Comics" }, // 1997 Mars Attacks High School
  21646: { publisher: "Topps Comics" }, // 1996 DragonHeart
  15721: { publisher: "Topps Comics" }, // 1993 Jurassic Park: Raptor
  50552: { publisher: "Topps Comics" }, // 1995 Jurassic Park Annual
  50656: { publisher: "Topps Comics" }, // 1995 Lady Rawhide Special Edition
  5183: { publisher: "Topps Comics" }, // 1994 Ray Bradbury Comics: Trilogy of Terror
  50273: { publisher: "Topps Comics" }, // 1993 Cadillacs and Dinosaurs Special Tyco Toys Edition
  21644: { publisher: "Topps Comics" }, // 1996 Mars Attacks Baseball Special
  5186: { publisher: "Topps Comics" }, // 1994 Star Wars: Tales of the Jedi: Dark Lords of the Sith / Topps Special Ashcan Edition
  5172: { publisher: "Topps Comics" }, // 1994 Victory
  5902: { publisher: "Topps Comics" }, // 1997 Xena: Warrior Princess: Year One
  15513: { publisher: "Topps Comics" }, // 1993 Topps Comics Presents
  40990: { publisher: "Topps Comics" }, // 1995 The X-Files Ashcan
  49870: { publisher: "Topps Comics" }, // 1994 Dracula Versus Zorro
  4889: { publisher: "Topps Comics" }, // 1993 Bombast
  4890: { publisher: "Topps Comics" }, // 1993 Captain Glory
  5182: { publisher: "Topps Comics" }, // 1993 Ray Bradbury Comics Special Edition
  49531: { publisher: "Topps Comics" }, // 1995 Xena
  5181: { publisher: "Topps Comics" }, // 1994 Ray Bradbury Comics: Martian Chronicles
  15157: { publisher: "Topps Comics" }, // 1993 Jack Kirby's Silver Star
  18750: { publisher: "Topps Comics" }, // 1995 Lady Rawhide Mini Comic
  55194: { publisher: "Topps Comics" }, // 1993 Jurassic Park
  50315: { publisher: "Topps Comics" }, // 1995 The Lone Ranger and Tonto
  121809: { publisher: "Topps Comics" }, // 1998 X-Files: Fight the Future
  208299: { publisher: "Topps Comics" }, // 1997 Jurassic Park 2 (Finnish reprint — 0 issues, harmless)
  138124: { publisher: "Topps Comics" }, // 1993 Jurassic Park
  120416: { publisher: "Topps Comics" }, // 1997 Xena: Warrior Princess 1st Appearance Collection
  50284: { publisher: "Topps Comics" }, // 1994 Mars Attacks Graphic Album
  36620: { publisher: "Topps Comics" }, // 1993 Jurassic Park
  49054: { publisher: "Topps Comics" }, // 1993 Bram Stoker's Dracula
  16343: { publisher: "Topps Comics" }, // 1997 The X-Files: Season One
  17094: { publisher: "Topps Comics" }, // 1995 The X-Files / Hero Illustrated Special
  55193: { publisher: "Topps Comics" }, // 1993 Jurassic Park
  62291: { publisher: "Topps Comics" }, // 1997 The X-Files AfterFlight
  // ── Current-IP-holder mislabels (same family as the TMNT-shows-IDW bug) ──
  // These 1990s Topps books got tagged with the modern rights holder
  // (IDW now owns Mars Attacks; Dynamite now owns Xena), so they were not
  // caught by the "Unknown Publisher" filter that produced the batch above.
  21642: { publisher: "Topps Comics" }, // 1994 Mars Attacks (mislabeled IDW)
  21643: { publisher: "Topps Comics" }, // 1995 Mars Attacks 7-issue mini (mislabeled IDW)
  46792: { publisher: "Topps Comics" }, // 1996 Mars Attacks one-shot (mislabeled IDW)
  5901: { publisher: "Topps Comics" }, // 1997 Xena: Warrior Princess 3-issue mini (mislabeled Dynamite)

  // ── Absolute Universe (2024-2025) — duplicate GCD series rows ───────────
  // Found 2026-08-03 investigating stale/wrong issue counts on the Absolute
  // line. Each real ongoing series (Batman/Superman/Wonder Woman) has 3-5
  // *other* `series` rows sharing the exact same title — issue_count 1 or 3,
  // years null or a single 2025 year, no distinct subtitle. These are almost
  // certainly GCD data-entry duplicates (alternate format/printing tracking
  // records), not real distinct volumes: the cross-volume cover-claim logic
  // in refreshSeriesSearchCache.js was assigning them the same cover as the
  // real series (nothing else in canonical_covers matches their bogus
  // title+year combo), and they clutter search with 4-6 near-identical
  // results for one actual book. The real rows (kept, not overridden):
  //   216143 Absolute Batman        (11+ issues, 2024-2025)
  //   217177 Absolute Superman      (10+ issues, 2025)
  //   216727 Absolute Wonder Woman  (10+ issues, 2024-2025)
  226633: { hide: true }, // dup of Absolute Batman (216143) — 1 issue, 2025
  226632: { hide: true }, // dup of Absolute Batman (216143) — 1 issue, 2025
  225230: { hide: true }, // dup of Absolute Batman (216143) — 1 issue, 2025
  224764: { hide: true }, // dup of Absolute Batman (216143) — 3 issues, no year
  225372: { hide: true }, // dup of Absolute Batman (216143) — 1 issue, 2025
  225232: { hide: true }, // dup of Absolute Superman (217177) — 1 issue, 2025
  224766: { hide: true }, // dup of Absolute Superman (217177) — 3 issues, no year
  226414: { hide: true }, // dup of Absolute Superman (217177) — 1 issue, no year
  226794: { hide: true }, // dup of Absolute Wonder Woman (216727) — 1 issue, 2025
  226793: { hide: true }, // dup of Absolute Wonder Woman (216727) — 1 issue, 2025
  224767: { hide: true }, // dup of Absolute Wonder Woman (216727) — 3 issues, no year
  225233: { hide: true }, // dup of Absolute Wonder Woman (216727) — 1 issue, 2025
};

// Look up an override by gcd_id (number or string-safe).
export function getSeriesOverride(gcdId) {
  if (gcdId == null) return null;
  return SERIES_OVERRIDES[Number(gcdId)] ?? null;
}
