"""Word-level timestamps for an episode's narration.

    python scripts/transcribe.py <audio file> <out.js> [model]

Writes an ES module: export default { duration, source, words: [{ w, s, e }] }
(word, start and end in seconds). A .js module rather than JSON so both the
Remotion bundle and plain Node scripts can import it without JSON import
attributes. Runs locally with faster-whisper on CPU; no account, no credits.
The timeline (episode-001/timeline.v3.js) anchors every shot to a phrase,
and shared/anchors.js finds each phrase's start in this word list.
"""
import json
import os
import subprocess
import sys

import numpy as np
from faster_whisper import WhisperModel

# Decode with the ffmpeg Remotion ships (handles wav, m4a, mp3, phone
# recordings) to 16 kHz mono float32, which is what Whisper wants. Avoids the
# PyAV decoder, whose API drifted out from under faster-whisper.
FFMPEG = os.path.join(os.path.dirname(__file__), "..", "node_modules", "@remotion",
                      "compositor-win32-x64-msvc", "ffmpeg.exe")


def load_audio(path):
    # Remotion's ffmpeg build has no raw f32 muxer; 16-bit WAV is enough.
    wav = subprocess.run(
        [FFMPEG, "-v", "error", "-i", path, "-ac", "1", "-ar", "16000",
         "-c:a", "pcm_s16le", "-f", "wav", "-"],
        check=True, capture_output=True,
    ).stdout
    data = wav.find(b"data")
    pcm = np.frombuffer(wav[data + 8:], dtype=np.int16)
    return pcm.astype(np.float32) / 32768.0

audio, out = sys.argv[1], sys.argv[2]
model_name = sys.argv[3] if len(sys.argv) > 3 else "small.en"

model = WhisperModel(model_name, device="cpu", compute_type="int8")
segments, info = model.transcribe(load_audio(audio), word_timestamps=True, vad_filter=True, beam_size=5)
words = []
for seg in segments:
    for w in seg.words or []:
        words.append({"w": w.word.strip(), "s": round(w.start, 3), "e": round(w.end, 3)})
    print(f"  {seg.end:7.1f}s  {seg.text.strip()[:70]}", flush=True)

payload = {"duration": round(info.duration, 3), "source": os.path.basename(audio), "words": words}
with open(out, "w", encoding="utf-8") as f:
    f.write("// Generated by scripts/transcribe.py. Do not edit by hand.\n")
    f.write("export default " + json.dumps(payload, separators=(",", ":")) + ";\n")
print(f"{len(words)} words, {info.duration:.1f}s -> {out}")
