# Narration from Tony's HeyGen voice clone, one API call per paragraph.
#
#   python scripts/tts-heygen.py <episode-dir> [model]
#
# Reads <episode-dir>/narration.tts.txt (paragraphs split by blank lines;
# "..." and [excited]/[laughs]-style cues shape the delivery), calls
# POST /v3/voices/speech with the ElevenLabs engine, caches each paragraph's
# audio + word timings in ~/Desktop/<episode>-assets/audio/tts/ (a rerun only
# pays for paragraphs whose text changed), joins them with PARA_GAP seconds of
# silence, polishes the result (scripts/polish-voice.py) to
# audio/NARRATION_HEYGEN.wav and writes <episode-dir>/narration.words.js.
#
# The API key comes from HEYGEN_API_KEY or ~/.heygen-key.
import hashlib
import json
import os
import re
import subprocess
import sys
import urllib.request
from pathlib import Path

import numpy as np
import soundfile as sf

VOICE_ID = "7064c951e1c34ae78a765287db940f45"  # "Anthony Jarina" (private clone)
PARA_GAP = 0.75
LEAD = 0.3
SR = 48000

ep_dir = Path(sys.argv[1]).resolve()
model = sys.argv[2] if len(sys.argv) > 2 else "eleven_v4"
assets = Path.home() / "Desktop" / f"{ep_dir.name}-assets" / "audio"
cache = assets / "tts"
cache.mkdir(parents=True, exist_ok=True)
key = os.environ.get("HEYGEN_API_KEY") or (Path.home() / ".heygen-key").read_text().strip()

# Spoken spellings back to how captions should read them. Token sequences,
# matched ignoring case and trailing punctuation.
DISPLAY = [
    (["one", "twenty-nine"], "129"), (["one", "thirty-seven"], "137"), (["one", "thirty"], "130"),
    (["one", "forty-one"], "141"), (["one", "forty-two"], "142"),
    (["kwah-pel"], "Coipel"), (["ex-cutioner's"], "X-Cutioner's"), (["strife"], "Stryfe"),
    (["comix", "catalog"], "ComixCatalog"), (["ninety-two"], "'92"), (["ninety-three"], "'93"),
    (["nineties"], "'90s"), (["sixty"], "60"), (["forty"], "40"), (["twelve"], "12"), (["ten"], "10"),
    (["want", "list"], "wantlist"),
]


def bare(w):
    return re.sub(r"[.,!?;:]+$", "", w).lower()


def to_display(words):
    out, i = [], 0
    while i < len(words):
        for seq, disp in DISPLAY:
            n = len(seq)
            if [bare(w["w"]) for w in words[i:i + n]] == seq:
                tail = re.search(r"[.,!?;:]+$", words[i + n - 1]["w"])
                out.append({"w": disp + (tail.group(0) if tail else ""), "s": words[i]["s"], "e": words[i + n - 1]["e"]})
                i += n
                break
        else:
            out.append(words[i])
            i += 1
    return out


def speak(text):
    h = hashlib.sha1(f"{VOICE_ID}|{model}|{text}".encode()).hexdigest()[:16]
    meta, audio = cache / f"{h}.json", cache / f"{h}.mp3"
    if not meta.exists():
        body = json.dumps({"text": text, "voice_id": VOICE_ID, "engine": "elevenlabs", "settings": {"model_id": model}}).encode()
        req = urllib.request.Request("https://api.heygen.com/v3/voices/speech", body, {"X-Api-Key": key, "Content-Type": "application/json"})
        data = json.load(urllib.request.urlopen(req, timeout=300))["data"]
        urllib.request.urlretrieve(data["audio_url"], audio)
        meta.write_text(json.dumps(data))
        print(f"  generated {h} ({len(text)} chars, {data['duration']:.1f}s)")
    data = json.loads(meta.read_text())
    x, sr = sf.read(audio, dtype="float32")
    if x.ndim > 1:
        x = x.mean(axis=1)
    if sr != SR:
        x = np.interp(np.arange(0, len(x) * SR / sr) * sr / SR, np.arange(len(x)), x).astype(np.float32)
    words = [{"w": w["word"], "s": w["start"], "e": w["end"]} for w in data.get("word_timestamps", [])
             if not re.match(r"^(<.*>|\[.*\])$", w["word"].strip())]
    return x, words


paras = [p.strip() for p in (ep_dir / "narration.tts.txt").read_text(encoding="utf-8").split("\n\n") if p.strip()]
chunks, words, t = [np.zeros(int(LEAD * SR), np.float32)], [], LEAD
for p in paras:
    x, ws = speak(p)
    words += [{"w": w["w"], "s": round(t + w["s"], 3), "e": round(t + w["e"], 3)} for w in ws]
    chunks += [x, np.zeros(int(PARA_GAP * SR), np.float32)]
    t += len(x) / SR + PARA_GAP
raw = assets / "NARRATION_HEYGEN_RAW.wav"
sf.write(raw, np.concatenate(chunks), SR, subtype="PCM_16")
out = assets / "NARRATION_HEYGEN.wav"
subprocess.run([sys.executable, str(Path(__file__).with_name("polish-voice.py")), str(raw), str(out)], check=True)

payload = {"duration": round(t, 3), "source": "NARRATION_HEYGEN.wav", "words": to_display(words)}
with open(ep_dir / "narration.words.js", "w", encoding="utf-8") as f:
    f.write("// Generated by scripts/tts-heygen.py. Do not edit by hand.\n")
    f.write("export default " + json.dumps(payload, separators=(",", ":")) + ";\n")
print(f"{len(paras)} paragraphs, {len(payload['words'])} words, {t:.1f}s -> {out}")
