// Edit decision list for Tony's narration recording (source seconds).
// Only applies when narration.words.js was made from this exact file.
//
// start:  drop everything before this (lead-in silence).
// cuts:   [from, to) ranges removed from the voice. Retakes: cut from the
//         first take's first word to the retake's first word. Restarts:
//         found by transcribing suspect spots on their own (whisper folds a
//         stumble into one stretched word in a full-file pass).
// pauses: dead air shortened to 0.4 s. Generated by
//         python scripts/find-pauses.py <NARRATION.wav> 41.9 0.6 0.4
//         (silence = below -44 dBFS), plus hand-trimmed breathy gaps.
export default {
  source: "NARRATION.m4a",
  start: 41.9,
  cuts: [
    [147.1, 149.95], // "That's how I got into X-Men." (said twice)
    [188.05, 192.55], // "and you don't need to do homework to enjoy this stuff." (twice)
    [219.9, 222.4], // "It's the team at their peak." (twice)
    [412.75, 414.92], // "The Scarlet Witch rewrites... The Scarlet Witch rewrites reality."
    [449.0, 451.5], // "It's a 12 issue, it's 12 issues that flipped..."
    [484.7, 486.85], // "Find a character you like." (twice)
    [532.25, 535.55], // "Don't turn reading comics into homework." (twice)
    [205.45, 206.4], // 1.4 s breathy pause after "Nobody's checking."
    [452.05, 452.65], // gap inside "it's... 12 issues"
  ],
  // Kept takes re-timed from a medium.en pass on just that stretch.
  patches: [
    { from: 412.5, to: 417.3, words: [{ w: "The", s: 414.95, e: 415.1 }, { w: "Scarlet", s: 415.1, e: 415.56 }, { w: "Witch", s: 415.56, e: 416.3 }, { w: "rewrites", s: 416.32, e: 417.3 }] },
    { from: 449.0, to: 453.7, words: [{ w: "It's", s: 451.56, e: 451.95 }, { w: "12", s: 452.96, e: 453.16 }, { w: "issues", s: 453.16, e: 453.5 }, { w: "that", s: 453.5, e: 453.7 }] },
  ],
  pauses:[[43.6, 43.95], [47.1, 48.1], [56.95, 57.3], [59.85, 60.25], [68.15, 69.0], [71.9, 72.25], [82.75, 83.45], [91.35, 91.65], [96.6, 97.0], [101.75, 102.0], [105.6, 105.85], [113.85, 114.55], [118.4, 118.6], [120.4, 121.15], [122.7, 123.0], [124.35, 124.7], [131.6, 131.95], [135.2, 135.55], [138.45, 138.9], [143.6, 143.85], [148.95, 149.95], [151.8, 152.1], [158.3, 158.8], [164.15, 164.75], [173.8, 174.2], [178.7, 179.0], [185.3, 185.55], [195.25, 196.2], [215.45, 215.85], [219.3, 219.9], [221.6, 222.4], [227.65, 228.1], [232.05, 232.3], [240.7, 241.05], [249.5, 249.9], [279.2, 279.45], [284.15, 285.25], [291.25, 291.75], [293.75, 294.9], [295.9, 296.2], [303.75, 304.6], [310.3, 311.05], [314.5, 314.75], [320.7, 320.9], [324.35, 325.05], [327.85, 328.15], [330.75, 331.0], [342.5, 342.95], [349.05, 349.25], [353.2, 353.5], [358.9, 359.15], [360.85, 361.85], [366.45, 366.8], [369.45, 369.8], [371.6, 372.35], [376.3, 376.7], [383.35, 384.15], [387.75, 388.1], [391.4, 392.0], [406.55, 406.75], [408.05, 408.85], [411.9, 412.6], [414.3, 414.75], [423.85, 424.25], [424.75, 424.95], [429.1, 429.5], [452.3, 452.5], [472.5, 472.9], [479.8, 480.15], [484.25, 484.75], [486.45, 487.1], [488.4, 488.7], [493.25, 493.6], [495.15, 495.55], [501.3, 501.85], [503.45, 503.75], [518.05, 518.25], [519.3, 520.0], [523.85, 524.05], [531.55, 532.1], [534.5, 535.5], [537.85, 538.2]],
};
